### ISSUE TITLE
New release with php8 compatibility

### ISSUE THREAD

**Issue by midahp** [maintaina-com/base#1]
@ralflang the newest tagged version does not have php8 support yet.
Can I create a new release for this? Maybe the version should be 6.1.0 because of the new php8 support?

**Comment by ralflang** [comment]
Looks like an oversight. I already upgraded the .horde.yml to ^7.4 || ^8 but did not release. 
Next would be 6.0.0alpha6 - we should not increase the feature digit before a stable release.

You can do it or I will do it by the weekend latest.
